ARG NGINX_IMAGE
FROM ${NGINX_IMAGE}
COPY yfeistai-classroom.conf /etc/nginx/conf.d/default.conf
RUN sed -i \
        -e 's/listen 443 ssl;/listen 443;/' \
        -e '/ssl_certificate /d' \
        -e '/ssl_certificate_key /d' \
        /etc/nginx/conf.d/default.conf \
    && nginx -t
